# Weights of yolov3_mobilenet_v1_voc
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/dygraph/ssd_mobilenet_v1_300_120e_voc.pdparams

slim: PruneQAT

pruner: Pruner

Pruner:
  criterion: fpgm
  pruned_params: ["conv2d_22.w_0", "conv2d_20.w_0", "conv2d_24"]
  pruned_ratios: [0.4, 0.4, 0,4]
  print_params: True


qat: QAT

QAT:
  quant_config: {
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear']}
  print_model: True
