epoch: 70

LearningRate:
  base_lr: 0.04
  schedulers:
  - !PiecewiseDecay
    milestones: [35, 55]
    gamma: [0.3, 0.1]
    use_warmup: false

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2