epoch: 40

LearningRate:
  base_lr: 0.05
  schedulers:
  - !PiecewiseDecay
    milestones: [15, 30]
    gamma: [0.5, 0.2]
    use_warmup: false

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2